name = "UpSums"
uuid = "e89f792d-5129-49c4-a257-c4eaea9201ed"
authors = ["Danny Robinson <dannyrobinson@gmx.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
